library(tm)
cname <- file.path("E:","AssignmentCorpus")
docs <- VCorpus(DirSource(cname))
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, stemDocument)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, content_transformer(PlainTextDocument))
dtm <- DocumentTermMatrix(docs)
freq <- colSums(as.matrix(dtm))
ord <- order(freq)
dtms <- removeSparseTerms(dtm, 0.50)
d <- dist(dtms, method="euclidian")
fit <- hclust(d=d, method="ward.D2")
plot(fit)
